const movies = [
    "The Shawshank Redemption",
    "Dilwale Dulhania Le Jayenge",
    "The Godfather",
    "Sholay",
    "Pulp Fiction",
    "Kabhi Khushi Kabhie Gham",
    "The Dark Knight",
    "3 Idiots",
    "Schindler's List",
    "Lagaan",
    "Fight Club",
    "DDLJ",
    "Forrest Gump",
    "My Name Is Khan",
    "Inception",
    "Rang De Basanti",
    "The Matrix",
    "Kuch Kuch Hota Hai",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Kabhi Alvida Naa Kehna",
    "Goodfellas",
    "Don",
    "The Silence of the Lambs",
    "Om Shanti Om",
    "The Empire Strikes Back",
    "Koi Mil Gaya",
    "The Lord of the Rings: The Two Towers",
    "Dil Chahta Hai",
    "Gladiator",
    "Dil To Pagal Hai",
    "Seven",
    "Kal Ho Naa Ho",
    "The Green Mile",
    "Mera Naam Joker",
    "The Usual Suspects",
    "Kabhi Haan Kabhi Naa",
    "American History X",
    "Golmaal",
    "The Lord of the Rings: The Return of the King",
    "Mughal-E-Azam",
    "The Pianist",
    "Kya Kehna",
    "The Departed",
    "Lage Raho Munna Bhai",
    "Inglourious Basterds",
    "Dil Se..",
    "The Prestige",
    "Gadar: Ek Prem Katha",
    "The Sixth Sense",
    "Dil Dhadakne Do",
    "Memento",
    "Dil",
    "Eternal Sunshine of the Spotless Mind",
    "Chak De! India",
    "The Shawshank Redemption",
    "Lage Raho Munna Bhai",
    "The Godfather",
    "Sholay",
    "Pulp Fiction",
    "Kabhi Khushi Kabhie Gham",
    "The Dark Knight",
    "3 Idiots",
    "Schindler's List",
    "Lagaan",
    "Fight Club",
    "DDLJ",
    "Forrest Gump",
    "My Name Is Khan",
    "Inception",
    "Rang De Basanti",
    "The Matrix",
    "Kuch Kuch Hota Hai",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Kabhi Alvida Naa Kehna",
    "Goodfellas",
    "Don",
    "The Silence of the Lambs",
    "Om Shanti Om",
    "The Empire Strikes Back",
    "Koi Mil Gaya",
    "The Lord of the Rings: The Two Towers",
    "Dil Chahta Hai",
    "Gladiator",
    "Dil To Pagal Hai",
    "Seven",
    "Kal Ho Naa Ho",
    "The Green Mile",
    "Mera Naam Joker",
    "The Usual Suspects",
    "Kabhi Haan Kabhi Naa",
    "American History X",
    "Golmaal",
    "The Lord of the Rings: The Return of the King",
    "Mughal-E-Azam",
    "The Pianist",
    "Kya Kehna",
    "The Departed",
    "Lage Raho Munna Bhai",
    "Inglourious Basterds",
    "Dil Se..",
    "The Prestige",
    "Gadar: Ek Prem Katha",
    "The Sixth Sense",
    "Dil Dhadakne Do",
    "Memento",
    "Dil",
    "Eternal Sunshine of the Spotless Mind",
    "Chak De! India",
  ];

  export const  getRandomUniqueMovies = () => {
  
    const randomMovies = [];
    const selectedIndices = new Set();
  
    while (randomMovies.length < 5) {
      const randomIndex = Math.floor(Math.random() * movies.length);
  
      if (!selectedIndices.has(randomIndex)) {
        selectedIndices.add(randomIndex);
        randomMovies.push(movies[randomIndex]);
      }
    }
  
    return randomMovies;
  }